# Generated by Django 5.2.6 on 2025-11-09 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '(임시)사용자', 'verbose_name_plural': '(임시)사용자 목록'},
        ),
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('external_user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='HR 사용자 ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='사용자명')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '외부 사용자',
                'verbose_name_plural': '외부 사용자 목록',
                'db_table': 'external_user',
                'indexes': [models.Index(fields=['email'], name='external_us_email_b7f570_idx'), models.Index(fields=['username'], name='external_us_usernam_2ba899_idx')],
            },
        ),
    ]
