# Generated by Django 5.2.6 on 2025-09-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.UUIDField(help_text='HR System에서 발급된 사용자 UUID', unique=True, verbose_name='외부 사용자 ID')),
                ('email', models.EmailField(db_index=True, help_text='사용자 이메일 주소 (검색 최적화 인덱스 포함)', max_length=254, verbose_name='이메일')),
                ('status', models.CharField(help_text='사용자 상태: pending, active, suspended 등', max_length=20, verbose_name='상태')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='core_system에서 데이터가 마지막으로 갱신된 시간', verbose_name='갱신일시')),
            ],
            options={
                'verbose_name': '외부 사용자',
                'verbose_name_plural': '외부 사용자 목록',
            },
        ),
    ]
