# Generated by Django 5.2.6 on 2025-09-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_externaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaluser',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('active', '활성'), ('suspended', '정지')], default='pending', help_text='사용자 상태: pending, active, suspended 등', max_length=20, verbose_name='상태'),
        ),
    ]
