# Generated by Django 5.2.6 on 2025-11-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_externaluser'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='externaluser',
            name='external_us_email_b7f570_idx',
        ),
        migrations.RemoveIndex(
            model_name='externaluser',
            name='external_us_usernam_2ba899_idx',
        ),
        migrations.AddField(
            model_name='externaluser',
            name='name',
            field=models.CharField(default='unknown', max_length=50, verbose_name='사용자 이름'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='externaluser',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='사용자 계정'),
        ),
    ]
