# Generated by Django 5.2.6 on 2025-09-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_externaluser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaluser',
            name='email',
            field=models.EmailField(db_index=True, help_text='사용자 이메일 주소 (검색 최적화 인덱스 포함)', max_length=254, unique=True, verbose_name='이메일'),
        ),
    ]
