# Generated by Django 5.2.6 on 2025-09-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_externaluser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaluser',
            name='external_user_id',
            field=models.UUIDField(editable=False, help_text='HR System에서 발급된 사용자 UUID', unique=True, verbose_name='외부 사용자 ID'),
        ),
    ]
