# Generated by Django 5.2.6 on 2025-09-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_externaluser_external_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaluser',
            name='external_user_id',
            field=models.UUIDField(help_text='HR System에서 발급된 사용자 UUID', unique=True, verbose_name='외부 사용자 ID'),
        ),
    ]
